config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "resolutions#index"
  resources :resolutions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resolution.rb
class Resolution < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :resolutions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :mobile_number, :role)
    end
  end
end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  before_action :find_resolution, only: [:show, :destroy]
  def index
    @user = User.find_by(first_name: params[:name]) || User.first #take first user if not available
    @resolutions = @user.resolutions
  end

  def show
  end

  def new
    @resolution = Resolution.new
  end

  def create
    @resolution = Resolution.new(resolution_params)

    respond_to do |format|
      if @resolution.save
        format.html { redirect_to resolution_url(@resolution), notice: 'Resolution was successfully created.' }
        format.json { render :show, status: :created, location: @resolution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resolution.destroy

    respond_to do |format|
      format.html { redirect_to resolutions_url, notice: 'Resolution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def resolution_params
    params.require(:resolution).permit!
  end

  def find_resolution
    @resolution = Resolution.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResolutionManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm px-3">
    <a class="navbar-brand fw-bold text-uppercase" href="/">Resolution Management</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <li class="nav-item px-2"><%= link_to "Ankit", resolutions_path(name: 'ankit'), class: 'nav-link h6 mb-0 text-dark'%></li>
            <li class="nav-item px-2"><%= link_to "Vinayak", resolutions_path(name: 'vinayak'), class: 'nav-link h6 mb-0 text-dark'%></li>
            <li class="nav-item px-2">
              <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: 'nav-link h6 mb-0 text-dark' %>
            </li>
          </li>
        <% else %>
          <li class="nav-item px-2">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link h6 mb-0 text-dark' %>
          </li>
          <li class="nav-item px-2">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link h6 mb-0 text-dark' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/resolutions/_form.html.erb
<div class="row mx-0">
  <div class="col-md-4 mx-auto border p-4 rounded-3 bg-light form-company">
    <%= form_with(model: resolution) do |form| %>
      <% if resolution.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(resolution.errors.count, "error") %> prohibited this place from being saved:</h2>

          <ul>
            <% resolution.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :Date, class: 'form-label' %><br />
        <%= form.date_field :date, autofocus: true, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :gym, class: 'form-label' %>
        <%= form.text_field :gym, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :fruit, class: 'form-label' %>
        <%= form.text_field :fruit, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :green_tea, class: 'form-label' %>
        <%= form.text_field :green_tea, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :no_junk_food, class: 'form-label' %>
        <%= form.text_field :no_junk_food, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :coaching, class: 'form-label' %>
        <%= form.text_field :coaching, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :program, class: 'form-label' %>
        <%= form.text_field :program, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :project, class: 'form-label' %>
        <%= form.text_field :project, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :speaking, class: 'form-label' %>
        <%= form.text_field :speaking, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :words, class: 'form-label' %>
        <%= form.text_field :words, class: 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :user, class: 'form-label' %>
        <%= form.collection_select :user_id, User.order(:id), :id, :first_name, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/resolutions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="d-flex align-items-center justify-content-center position-relative">
    <% if @user.first_name == 'ankit' %>
      <h2 class="text-center p-3 text-uppercase">Ankit Lists</h2>
    <% else %>
      <h2 class="text-center p-3 text-uppercase">Vinayak Lists</h2>
    <% end %>

    <%= link_to 'New Resolution', new_resolution_path, class: 'position-absolute end-0 bg-primary px-4 py-2 text-white rounded-3 mr-2 text-decoration-none' %>
  </div>
  <div class="table-responsive text-center">
    <table class="table table-striped table-hover border border-dark">
      <thead>
        <tr>
          <% if @user.first_name == 'ankit' %>
            <th>Date</th>
            <th>Coaching</th>
            <th>Program</th>
            <th>Speaking</th>
            <th>Project</th>
            <th>Words</th>
          <% else %>
            <th>Date</th>
            <th>Gym</th>
            <th>Fruit</th>
            <th>Gren Tea</th>
            <th>No Junk Food</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @resolutions.each do |resolution| %>
          <tr>
            <% if @user.first_name == 'ankit' %>
              <td><%= resolution&.date&.to_time&.strftime('%e %B') %></td>
              <td><%= resolution.coaching %></td>
              <td><%= resolution.program %></td>
              <td><%= resolution.speaking %></td>
              <td><%= resolution.project %></td>
              <td><%= resolution.words %></td>
            <% else %>
              <td><%= resolution&.date&.to_time&.strftime('%e %B') %></td>
              <td><%= resolution.gym %></td>
              <td><%= resolution.fruit %></td>
              <td><%= resolution.green_tea %></td>
              <td><%= resolution.no_junk_food %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>  
<br>

app/views/resolutions/new.html.erb
<h2 class="text-center p-3 text-uppercase">New Resolution</h2>

<%= render 'form', resolution: @resolution %>

<%= link_to 'Back', resolutions_path, class: 'px-4 py-2 text-dark rounded-3 my-3 d-block text-end bg-transparent' %>

app/views/resolutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @resolution.gym %>
</p>

<p>
  <strong>Node name:</strong>
  <%= @resolution.gym %>
</p>

<%= link_to 'Back', resolutions_path %>